name        : fluid-soundfont
version     : '3'
release     : 1
source      :
    - http://http.debian.net/debian/pool/main/f/fluid-soundfont/fluid-soundfont_3.1.orig.tar.gz : 2621acaa1c78e4abdb24bdd163230cc577e61276936d6aa6e3180582142f0343
license     : MIT
component   : multimedia.audio
summary     : Modern SoundFont for use with MIDI synthesizers
description :
    Fluid is a SoundFont for use with any modern MIDI synthesiser like FluidSynth.
install     : |
    install -Dm00644 FluidR3_GM.sf2 $installdir/usr/share/sounds/sf2/FluidR3.sf2
    install -Dm00644 COPYING $installdir/usr/share/doc/fluid-soundfont/COPYING
    install -Dm00644 README $installdir/usr/share/doc/fluid-soundfont/README